export const AC: string
export const AD: string
export const AE: string
export const AF: string
export const AG: string
export const AI: string
export const AL: string
export const AM: string
export const AO: string
export const AQ: string
export const AR: string
export const AS: string
export const AT: string
export const AU: string
export const AW: string
export const AX: string
export const AZ: string
export const BA: string
export const BB: string
export const BD: string
export const BE: string
export const BF: string
export const BG: string
export const BH: string
export const BI: string
export const BJ: string
export const BL: string
export const BM: string
export const BN: string
export const BO: string
export const BQ: string
export const BR: string
export const BS: string
export const BT: string
export const BV: string
export const BW: string
export const BY: string
export const BZ: string
export const CA: string
export const CC: string
export const CD: string
export const CF: string
export const CG: string
export const CH: string
export const CI: string
export const CK: string
export const CL: string
export const CM: string
export const CN: string
export const CO: string
export const CR: string
export const CU: string
export const CV: string
export const CW: string
export const CX: string
export const CY: string
export const CZ: string
export const DE: string
export const DJ: string
export const DK: string
export const DM: string
export const DO: string
export const DZ: string
export const EC: string
export const EE: string
export const EG: string
export const EH: string
export const ER: string
export const ES: string
export const ET: string
export const EU: string
export const FI: string
export const FJ: string
export const FK: string
export const FM: string
export const FO: string
export const FR: string
export const GA: string
export const GB: string
export const GD: string
export const GE: string
export const GF: string
export const GG: string
export const GH: string
export const GI: string
export const GL: string
export const GM: string
export const GN: string
export const GP: string
export const GQ: string
export const GR: string
export const GS: string
export const GT: string
export const GU: string
export const GW: string
export const GY: string
export const HK: string
export const HM: string
export const HN: string
export const HR: string
export const HT: string
export const HU: string
export const IC: string
export const ID: string
export const IE: string
export const IL: string
export const IM: string
export const IN: string
export const IO: string
export const IQ: string
export const IR: string
export const IS: string
export const IT: string
export const JE: string
export const JM: string
export const JO: string
export const JP: string
export const KE: string
export const KG: string
export const KH: string
export const KI: string
export const KM: string
export const KN: string
export const KP: string
export const KR: string
export const KW: string
export const KY: string
export const KZ: string
export const LA: string
export const LB: string
export const LC: string
export const LI: string
export const LK: string
export const LR: string
export const LS: string
export const LT: string
export const LU: string
export const LV: string
export const LY: string
export const MA: string
export const MC: string
export const MD: string
export const ME: string
export const MF: string
export const MG: string
export const MH: string
export const MK: string
export const ML: string
export const MM: string
export const MN: string
export const MO: string
export const MP: string
export const MQ: string
export const MR: string
export const MS: string
export const MT: string
export const MU: string
export const MV: string
export const MW: string
export const MX: string
export const MY: string
export const MZ: string
export const NA: string
export const NC: string
export const NE: string
export const NF: string
export const NG: string
export const NI: string
export const NL: string
export const NO: string
export const NP: string
export const NR: string
export const NU: string
export const NZ: string
export const OM: string
export const PA: string
export const PE: string
export const PF: string
export const PG: string
export const PH: string
export const PK: string
export const PL: string
export const PM: string
export const PN: string
export const PR: string
export const PS: string
export const PT: string
export const PW: string
export const PY: string
export const QA: string
export const RE: string
export const RO: string
export const RS: string
export const RU: string
export const RW: string
export const SA: string
export const SB: string
export const SC: string
export const SD: string
export const SE: string
export const SG: string
export const SH: string
export const SI: string
export const SJ: string
export const SK: string
export const SL: string
export const SM: string
export const SN: string
export const SO: string
export const SR: string
export const SS: string
export const ST: string
export const SV: string
export const SX: string
export const SY: string
export const SZ: string
export const TA: string
export const TC: string
export const TD: string
export const TF: string
export const TG: string
export const TH: string
export const TJ: string
export const TK: string
export const TL: string
export const TM: string
export const TN: string
export const TO: string
export const TR: string
export const TT: string
export const TV: string
export const TW: string
export const TZ: string
export const UA: string
export const UG: string
export const UM: string
export const US: string
export const UY: string
export const UZ: string
export const VA: string
export const VC: string
export const VE: string
export const VG: string
export const VI: string
export const VN: string
export const VU: string
export const WF: string
export const WS: string
export const XK: string
export const YE: string
export const YT: string
export const ZA: string
export const ZM: string
export const ZW: string
